"""
track_visdrone_tensorrt_fp16.py
--------------------------------
Run a custom VisDrone YOLO TensorRT FP16 engine with BoT-SORT/ByteTrack on
VisDrone2019-MOT test-dev and save one MOT-Challenge prediction file per
sequence.

Required files beside this script:
    infer.py

Required TensorRT files:
    best.engine
    best.names                  generated by export_tensorrt.py

Output format:
    <frame>,<id>,<bb_left>,<bb_top>,<bb_width>,<bb_height>,<conf>,<class>,-1,-1

Examples:
    # Use all defaults
    python track_visdrone_tensorrt_fp16.py

    # Select engine and tracker
    python track_visdrone_tensorrt_fp16.py \
        --model runs/detect/train/weights/best.engine \
        --tracker visdrone_bytetrack.yaml

    # Full configuration
    python track_visdrone_tensorrt_fp16.py \
        --model runs/detect/train/weights/best.engine \
        --sequences-dir datasets/VisDrone/VisDrone2019-MOT-test-dev/sequences \
        --tracker visdrone_botsort.yaml \
        --output-dir runs/tracking/visdrone/test-dev-tensorrt-fp16/annotations \
        --imgsz 1280 --conf 0.10 --iou 0.60 --device 0
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure the sibling infer.py is imported even when this script is launched
# from another working directory.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))


def _import_infer_helpers():
    """Import infer.py lazily so --help works before runtime dependencies load."""
    try:
        from infer import _load_model, _reset_tracker
    except ImportError as exc:
        sys.exit(
            "[ERROR] Could not import the sibling infer.py. Keep infer.py and "
            f"this script in the same directory. Details: {exc}"
        )
    return _load_model, _reset_tracker


# ── Default configuration ─────────────────────────────────────────────────────
DEFAULT_MODEL_PATH = "runs/detect/train/weights/best.engine"

DEFAULT_SEQUENCES_DIR = (
    "datasets/VisDrone/VisDrone2019-MOT-test-dev/sequences"
)

DEFAULT_TRACKER_CONFIG = "visdrone_botsort.yaml"

DEFAULT_OUTPUT_DIR = (
    "runs/tracking/visdrone/test-dev-tensorrt-fp16/annotations"
)

DEFAULT_CONF_THRESH = 0.10
DEFAULT_IOU_THRESH = 0.60
DEFAULT_IMG_SIZE = 1280

# YOLO zero-based class index -> VisDrone one-based class ID.
YOLO_TO_VISDRONE_CLASS = {
    0: 1,   # pedestrian
    1: 2,   # people
    2: 3,   # bicycle
    3: 4,   # car
    4: 5,   # van
    5: 6,   # truck
    6: 7,   # tricycle
    7: 8,   # awning-tricycle
    8: 9,   # bus
    9: 10,  # motor
}
# ──────────────────────────────────────────────────────────────────────────────


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run a custom YOLO TensorRT engine with BoT-SORT/ByteTrack on "
            "VisDrone-MOT sequences and save MOT-format prediction files."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--model",
        type=Path,
        default=Path(DEFAULT_MODEL_PATH),
        help=(
            "Path to the TensorRT .engine file. A matching .names file must "
            "exist beside it."
        ),
    )

    parser.add_argument(
        "--sequences-dir",
        type=Path,
        default=Path(DEFAULT_SEQUENCES_DIR),
        help="Directory containing one image directory per VisDrone sequence.",
    )

    parser.add_argument(
        "--tracker",
        type=Path,
        default=Path(DEFAULT_TRACKER_CONFIG),
        help="Path to the BoT-SORT or ByteTrack YAML configuration.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(DEFAULT_OUTPUT_DIR),
        help="Directory in which one MOT .txt file is saved per sequence.",
    )

    parser.add_argument(
        "--imgsz",
        type=int,
        default=DEFAULT_IMG_SIZE,
        help=(
            "Inference image size. For a static TensorRT engine, this must "
            "match the size used during export."
        ),
    )

    parser.add_argument(
        "--conf",
        type=float,
        default=DEFAULT_CONF_THRESH,
        help="Detection confidence threshold passed to model.track().",
    )

    parser.add_argument(
        "--iou",
        type=float,
        default=DEFAULT_IOU_THRESH,
        help="NMS IoU threshold passed to model.track().",
    )

    parser.add_argument(
        "--device",
        default=None,
        help=(
            "CUDA device passed to Ultralytics, for example 0, 1, or cuda:0. "
            "Omit it to use the TensorRT/Ultralytics default."
        ),
    )

    parser.add_argument(
        "--sequence",
        action="append",
        default=None,
        metavar="NAME",
        help=(
            "Process only the named sequence. Repeat this option to select "
            "multiple sequences. By default, all sequence directories run."
        ),
    )

    return parser.parse_args()


def _resolve_required_file(path_value: Path, description: str) -> Path:
    """Resolve a required local file and stop with a clear error if missing."""
    path = path_value.expanduser()

    if not path.is_file():
        sys.exit(f"[ERROR] {description} not found: {path.resolve()}")

    return path.resolve()


def _validate_args(args: argparse.Namespace, model_path: Path) -> None:
    """Validate CLI settings important for TensorRT tracking."""
    if model_path.suffix.lower() != ".engine":
        sys.exit(
            f"[ERROR] --model must point to a .engine file: {model_path}"
        )

    names_path = model_path.with_suffix(".names")

    if not names_path.is_file():
        sys.exit(
            f"[ERROR] TensorRT class-name sidecar not found: {names_path}\n"
            "        Re-export the engine with export_tensorrt.py, or place "
            "the matching .names file beside the engine."
        )

    if args.imgsz <= 0:
        sys.exit("[ERROR] --imgsz must be greater than 0.")

    if not 0.0 <= args.conf <= 1.0:
        sys.exit("[ERROR] --conf must be between 0 and 1.")

    if not 0.0 <= args.iou <= 1.0:
        sys.exit("[ERROR] --iou must be between 0 and 1.")


def _collect_sequence_paths(
    sequence_root: Path,
    selected_names: list[str] | None,
) -> list[Path]:
    """Collect all sequences, or only those selected with --sequence."""
    all_paths = sorted(
        path for path in sequence_root.iterdir() if path.is_dir()
    )

    if not all_paths:
        sys.exit(
            f"[ERROR] No sequence directories found in: "
            f"{sequence_root.resolve()}"
        )

    if not selected_names:
        return all_paths

    by_name = {path.name: path for path in all_paths}

    missing = [
        name for name in selected_names
        if name not in by_name
    ]

    if missing:
        available_preview = ", ".join(sorted(by_name)[:10])

        sys.exit(
            "[ERROR] Requested sequence(s) not found: "
            + ", ".join(missing)
            + f"\n        Available examples: {available_preview}"
        )

    # Preserve CLI order while removing duplicate names.
    unique_names = list(dict.fromkeys(selected_names))

    return [by_name[name] for name in unique_names]


def track_visdrone(args: argparse.Namespace) -> None:
    model_path = _resolve_required_file(
        args.model,
        "TensorRT engine",
    )

    tracker_path = _resolve_required_file(
        args.tracker,
        "Tracker config",
    )

    _validate_args(args, model_path)

    sequence_root = args.sequences_dir.expanduser()

    if not sequence_root.is_dir():
        sys.exit(
            f"[ERROR] Sequences directory not found: "
            f"{sequence_root.resolve()}"
        )

    sequence_root = sequence_root.resolve()
    output_dir = args.output_dir.expanduser().resolve()

    sequence_paths = _collect_sequence_paths(
        sequence_root,
        args.sequence,
    )

    print(f"Loading TensorRT model : {model_path}")
    print(f"Class names file       : {model_path.with_suffix('.names')}")
    print(f"Sequences directory    : {sequence_root}")
    print(f"Tracker config         : {tracker_path}")
    print(f"Output directory       : {output_dir}")
    print(f"Image size             : {args.imgsz}")
    print(f"Confidence / NMS IoU   : {args.conf} / {args.iou}")
    print(f"Device                 : {args.device or 'default'}")
    print(f"Found {len(sequence_paths)} sequence(s)")

    _load_model, _reset_tracker = _import_infer_helpers()

    # _load_model() validates the 10-class taxonomy and injects the class names
    # from the .names sidecar into the TensorRT backend.
    model = _load_model(model_path)

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    track_kwargs: dict[str, object] = {
        "tracker": str(tracker_path),
        "imgsz": args.imgsz,
        "conf": args.conf,
        "iou": args.iou,
        "persist": True,
        "stream": True,
        "verbose": False,
        "save": False,
    }

    if args.device is not None:
        track_kwargs["device"] = args.device

    for sequence_index, sequence_path in enumerate(
        sequence_paths,
        start=1,
    ):
        sequence_name = sequence_path.name
        output_file = output_dir / f"{sequence_name}.txt"

        print(
            f"\n[{sequence_index}/{len(sequence_paths)}] "
            f"{sequence_name} -> {output_file}"
        )

        # Do not carry IDs or Kalman-filter state from one independent sequence
        # into the next sequence.
        _reset_tracker(model)

        results = model.track(
            source=str(sequence_path),
            **track_kwargs,
        )

        row_count = 0

        with output_file.open(
            "w",
            encoding="utf-8",
            newline="\n",
        ) as output:
            for frame_id, result in enumerate(
                results,
                start=1,
            ):
                boxes_result = getattr(
                    result,
                    "boxes",
                    None,
                )

                if (
                    boxes_result is None
                    or boxes_result.id is None
                ):
                    continue

                boxes = boxes_result.xyxy.cpu().numpy()
                track_ids = boxes_result.id.int().cpu().numpy()
                confidences = boxes_result.conf.cpu().numpy()
                class_indices = boxes_result.cls.int().cpu().numpy()

                for box, track_id, confidence, class_index in zip(
                    boxes,
                    track_ids,
                    confidences,
                    class_indices,
                ):
                    class_index_int = int(class_index)

                    if class_index_int not in YOLO_TO_VISDRONE_CLASS:
                        raise ValueError(
                            "TensorRT model returned an unexpected class "
                            f"index: {class_index_int}"
                        )

                    x1, y1, x2, y2 = (
                        float(value)
                        for value in box
                    )

                    width = max(0.0, x2 - x1)
                    height = max(0.0, y2 - y1)

                    visdrone_class = (
                        YOLO_TO_VISDRONE_CLASS[class_index_int]
                    )

                    output.write(
                        f"{frame_id},{int(track_id)},"
                        f"{x1:.2f},{y1:.2f},"
                        f"{width:.2f},{height:.2f},"
                        f"{float(confidence):.4f},"
                        f"{visdrone_class},-1,-1\n"
                    )

                    row_count += 1

        print(f"  Saved {row_count:,} tracking rows")

    print(f"\nDone. TensorRT predictions: {output_dir}")
    print("Evaluate them with:")

    print(
        "  python eval_visdrone.py "
        f"--pred-dir {output_dir} "
        "--out evaluate_results_tensorrt_fp16.json"
    )


def main() -> None:
    args = parse_args()
    track_visdrone(args)


if __name__ == "__main__":
    main()