"""
visualize_botsort.py
--------------------
Batch visualize all MOT sequences in VisDrone2019-MOT-test-dev (or any custom
sequence root) using annotations generated by BoT-SORT (or any MOT-challenge
annotation files).

This script imports and uses the core `visualise` engine from `visualize.py`
to render bounding boxes, track ID labels, class colours, and legend on every
frame, saving the output as annotated videos (.mp4) or frame folders.

Usage examples
--------------
# Basic – run with default VisDrone test-dev sequences and BoT-SORT annotations:
python visualize_botsort.py

# Specify custom output directory and minimum confidence:
python visualize_botsort.py --out-dir vis_output/botsort_test_dev --conf-min 0.2

# Save individual frames instead of MP4 videos:
python visualize_botsort.py --frames

# Visualise only the 5 tracked VisDrone classes (pedestrian, car, van, truck, bus):
python visualize_botsort.py --tracked-only
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

from visualize import visualise


# ── Configuration Defaults ─────────────────────────────────────────────────────
DEFAULT_SEQ_ROOT = "datasets/VisDrone/VisDrone2019-MOT-test-dev/sequences"
DEFAULT_ANN_ROOT = "bytetrack/visdrone/test-dev/annotations"
DEFAULT_OUT_DIR  = "vis_output/bytetrack"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Batch visualize all sequences with BoT-SORT MOT annotations.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--seq-root", type=Path, default=Path(DEFAULT_SEQ_ROOT),
                   help="Root directory containing sequence folders.")
    p.add_argument("--ann-root", type=Path, default=Path(DEFAULT_ANN_ROOT),
                   help="Directory containing MOT-challenge .txt annotation files.")
    p.add_argument("--out-dir", type=Path, default=Path(DEFAULT_OUT_DIR),
                   help="Directory where output videos (or frame folders) will be saved.")
    p.add_argument("--dataset", default="visdrone", choices=["visdrone", "uavdt"],
                   help="Dataset type (determines class names and taxonomy).")
    p.add_argument("--fps", type=float, default=25.0,
                   help="Output video frame rate.")
    p.add_argument("--start", type=int, default=1,
                   help="First frame to render per sequence (1-indexed).")
    p.add_argument("--end", type=int, default=None,
                   help="Last frame to render per sequence (inclusive). Defaults to last frame.")
    p.add_argument("--conf-min", type=float, default=0.0,
                   help="Minimum detection confidence threshold (0.0 = show all).")
    p.add_argument("--frames", action="store_true",
                   help="Save individual annotated PNG/JPG frames instead of MP4 videos.")
    p.add_argument("--no-id", action="store_true",
                   help="Suppress track ID labels on bounding boxes.")
    p.add_argument("--ignore-cls", type=int, nargs="*", default=[0],
                   help="Class IDs to skip entirely (default: 0 = VisDrone ignore region).")
    p.add_argument("--tracked-only", action="store_true",
                   help="Show only the 5 VisDrone tracked classes (pedestrian, car, van, truck, bus).")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    seq_root = args.seq_root.resolve()
    ann_root = args.ann_root.resolve()
    out_dir  = args.out_dir.resolve()

    if not seq_root.is_dir():
        sys.exit(f"[ERROR] Sequences root directory not found: {seq_root}")
    if not ann_root.is_dir():
        sys.exit(f"[ERROR] Annotations root directory not found: {ann_root}")

    # Collect all sequence subdirectories
    sequence_dirs = sorted([d for d in seq_root.iterdir() if d.is_dir()])
    if not sequence_dirs:
        sys.exit(f"[ERROR] No sequence subdirectories found in: {seq_root}")

    print(f"=== BoT-SORT Batch Visualization ===")
    print(f"Sequences root   : {seq_root} ({len(sequence_dirs)} sequences found)")
    print(f"Annotations root : {ann_root}")
    print(f"Output directory : {out_dir}")
    print(f"Output mode      : {'Individual frames' if args.frames else f'MP4 Video (@ {args.fps} FPS)'}")
    print(f"Confidence min   : {args.conf_min}")
    print("====================================")

    out_dir.mkdir(parents=True, exist_ok=True)

    start_time = time.time()
    success_count = 0
    missing_ann_count = 0

    for i, seq_dir in enumerate(sequence_dirs, 1):
        seq_name = seq_dir.name
        ann_file = ann_root / f"{seq_name}.txt"

        print(f"\n[{i}/{len(sequence_dirs)}] Processing sequence: {seq_name}")

        if not ann_file.exists():
            print(f"  [WARN] Annotation file not found: {ann_file}")
            print(f"  Skipping {seq_name}...")
            missing_ann_count += 1
            continue

        # Determine output path for this sequence
        if args.frames:
            seq_out_path = out_dir / seq_name
        else:
            seq_out_path = out_dir / f"{seq_name}.mp4"

        try:
            visualise(
                seq_dir        = seq_dir,
                ann_path       = ann_file,
                out_path       = seq_out_path,
                dataset        = args.dataset,
                fps            = args.fps,
                start          = args.start,
                end            = args.end,
                save_frames    = args.frames,
                show_id        = not args.no_id,
                conf_min       = args.conf_min,
                ignore_classes = set(args.ignore_cls) if args.ignore_cls else set(),
                all_classes    = not args.tracked_only,
            )
            success_count += 1
        except Exception as e:
            print(f"  [ERROR] Failed to visualize {seq_name}: {e}")

    total_time = time.time() - start_time
    print("\n====================================")
    print(f"Batch visualization complete in {total_time:.2f}s!")
    print(f"  Successfully processed : {success_count}/{len(sequence_dirs)} sequences")
    if missing_ann_count > 0:
        print(f"  Missing annotations    : {missing_ann_count} sequences")
    print(f"  Output saved to        : {out_dir}")
    print("====================================")


if __name__ == "__main__":
    main()
